#!/usr/bin/env python

# SCsub

Import('env')
Import('env_modules')

env_godotnect = env_modules.Clone()

libfreenect_basedir = "#thirdparty/libfreenect/"

libfreenect_folders = ["include/", "wrappers/cpp/" ]

libfreenect_dirs = [libfreenect_basedir + folder for folder in libfreenect_folders]

libusb_dirs = "#thirdparty/libusb/libusb/"

env_godotnect.Prepend(CPPPATH=[libfreenect_dirs, libusb_dirs])

module_obj = []

env_godotnect.add_source_files(module_obj, "*.cpp")

env.modules_sources += module_obj

env.Append(LIBPATH=["/home/eamondo2/build/libfreenect/build/lib/"])

env.Append(LIBS=["freenect"])